name: quill_html_editor
description: HTML rich text editor for Android, iOS, and Web, it is built with the powerful Quill Js library. Which is an open source WYSIWYG editor built for the modern web.

version: 2.2.6
homepage: https://github.com/the-airbender/quill_html_editor
repository: https://github.com/the-airbender/quill_html_editor
maintainer: Pavan Kumar Nagulavancha

environment:
  sdk: '>=2.18.1 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  ##### For image picker widget
  file_picker: ^6.0.0
  ##### For webveiwx widget
  http: ^1.1.0
  path: ^1.8.2
  pointer_interceptor: ^0.9.3+6
  uuid: ^4.1.0
  webview_flutter: ^4.4.1
  webview_flutter_android: ^3.12.0
  webview_flutter_platform_interface: ^2.5.0
  webview_flutter_wkwebview: ^3.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: quill_html_editor
      ios:
        default_package: quill_html_editor
      web:
        default_package: quill_html_editor
  assets:
      - packages/quill_html_editor/assets/camera_roll_icon.png
      - packages/quill_html_editor/assets/h1_dark.png
      - packages/quill_html_editor/assets/h2_dark.png
      - packages/quill_html_editor/assets/h3_dark.png
      - packages/quill_html_editor/assets/h4_dark.png
      - packages/quill_html_editor/assets/h5_dark.png
      - packages/quill_html_editor/assets/edit_table.png
      - packages/quill_html_editor/assets/insert_table.png
      - packages/quill_html_editor/assets/delete_column.png
      - packages/quill_html_editor/assets/delete_row.png
      - packages/quill_html_editor/assets/delete_table.png
      - packages/quill_html_editor/assets/insert_column_left.png
      - packages/quill_html_editor/assets/insert_row_above.png
      - packages/quill_html_editor/assets/insert_row_below.png
      - packages/quill_html_editor/assets/insert_column_right.png
      - packages/quill_html_editor/assets/superscript.png
      - packages/quill_html_editor/assets/subscript.png
      - packages/quill_html_editor/assets/scripts/quill_2.0.0_4_min.js
