name: quill_html_editor
description: HTML rich text editor for Android, iOS and Web, using the QuilJS library.
version: 2.0.1
homepage: https://github.com/the-airbender/quill_html_editor
repository: https://github.com/the-airbender/quill_html_editor
maintainer: Pavan Kumar

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  webviewx_plus: ^0.3.2
  file_picker: ^5.2.2
  universal_io: ^2.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - packages/quill_html_editor/assets/camera_roll_icon.png
